### ISSUE TITLE
Release as a Flatpak

### ISSUE THREAD

**Issue by CarsonBurke** [cosmic-utils/minimon-applet#19]
Per discussion [here](https://chat.pop-os.org/pop-os/pl/8a4br5g4opnzfm53jh694zeu6y) Flatpak has "not been done before" for applets, but is a recommended way to package.

I have not packaged a flatpak before, but I am happy to give it a shot.

**Comment by Hyperchaotic** [comment]
Might need extra permission for sysfs access to HW data for CPU temp and AMD stats, json snippet:

```
"finish-args": [
  "--filesystem=/sys/class/hwmon:ro",
  "--filesystem=/sys/class/drm:ro",
  "--filesystem=/sys/devices:ro",
  "--device=all"
]

```

Not sure how to handle the nvml Nvidia library/dependency.

**Comment by CarsonBurke** [comment]
#54 Draft PR

We'll also probably want a more designed logo to publish on Flathub. @Hyperchaotic any ideas on design, and are you able to make one or have a person? I have a friend who can make one but it won't be the highest quality.

**Comment by CarsonBurke** [comment]
Could someone try to build [this](https://github.com/CarsonBurke/flathub/tree/new-pr) and tell me if they are successful or hit errors please? I'm getting the same smithay error I had before that might just be something wrong with my setup.

Build with 
```
flatpak run org.flatpak.Builder --force-clean --sandbox --user --install --install-deps-from=flathub --ccache --mirror-screenshots-url=https://dl.flathub.org/media/ --repo=repo builddir io.github.cosmicUtils.cosmicAppletMinimon.json```

**Comment by Hyperchaotic** [comment]
I'll try to run that later. I wonder if it would be different building in a fresh Distrobox instance with a different build dir.

**Comment by CarsonBurke** [comment]
Yep I'm going to give that a shot as well. There are just so many dependencies that I'm hesitant to make a vm that will use so much storage space

**Comment by Hyperchaotic** [comment]
```
Initializing build dir
Committing stage init to cache
Starting build of io.github.cosmicUtils.cosmicAppletMinimon
========================================================================
Building module just in /home/hyper/code/pr/minimon-applet/.flatpak-builder/build/just-1
========================================================================
Running: install -Dm0755 just /app/bin/just
compressing debuginfo in: /home/hyper/code/pr/minimon-applet/.flatpak-builder/rofiles/rofiles-2iowAK/files/bin/just
processing: /home/hyper/code/pr/minimon-applet/.flatpak-builder/rofiles/rofiles-2iowAK/files/bin/just
[24] .debug_aranges compressed -> .zdebug_aranges (20208 => 5086 25.17%)
[25] .debug_info compressed -> .zdebug_info (623454 => 233625 37.47%)
[26] .debug_abbrev compressed -> .zdebug_abbrev (16667 => 1426 8.56%)
[27] .debug_line compressed -> .zdebug_line (272101 => 113203 41.60%)
[28] .debug_frame compressed -> .zdebug_frame (17312 => 4584 26.48%)
[29] .debug_str compressed -> .zdebug_str (857502 => 146449 17.08%)
[30] .debug_ranges compressed -> .zdebug_ranges (389440 => 41121 10.56%)
[33] Updating section string table
stripping /home/hyper/code/pr/minimon-applet/.flatpak-builder/rofiles/rofiles-2iowAK/files/bin/just to /home/hyper/code/pr/minimon-applet/.flatpak-builder/rofiles/rofiles-2iowAK/files/lib/debug/bin/just.debug
Committing stage build-just to cache
========================================================================
Building module cosmic-applet-minimon in /home/hyper/code/pr/minimon-applet/.flatpak-builder/build/cosmic-applet-minimon-1
========================================================================
Running: just vendor
error: No justfile found
Error: module cosmic-applet-minimon: Child process exited with code 1
```

**Comment by CarsonBurke** [comment]
That's confusing

**Comment by Hyperchaotic** [comment]
Perhaps I messed up? I cloned a fresh copy of minimon and then copied your io.github.cosmicUtils.cosmicAppletMinimon.json on top overwriting the existing, and put your cargo-sources.json in ./flatpak/ and then ran the command.

**Comment by CarsonBurke** [comment]
I don't think you should be overwriting anything. The idea is the run the Flatpak builder in the flathub: new-pr repo I linked. You don't even need to have minimon on your computer, it should build everything from the repo url found in the `<AppId>.json`

![Image](https://github.com/user-attachments/assets/a298e287-d24d-45ae-98f5-c8ff2fbc9ec9)

Basically this flathub: new-pr repo is the thing we submit to Flathub that tells them how to build our project.

**Comment by Hyperchaotic** [comment]
Ooh I see, I checked out your repo+pr and ran it.

[output.txt](https://github.com/user-attachments/files/20763871/output.txt)

**Comment by CarsonBurke** [comment]
Thanks. Weird that it failed with libcosmic :/. @edfloreshz Would you be willing to lend a hand?

**Comment by edfloreshz** [comment]
Sure, let's discuss this further on Mattermost and then share our finding here, sound good?

**Comment by CarsonBurke** [comment]
![Image](https://github.com/user-attachments/assets/7a1d0419-ff4a-4213-9a9b-ecd708595fa6)

can be acquired from the new [cosmic flatpak repository](https://github.com/pop-os/cosmic-flatpak)
```
flatpak remote-add --if-not-exists --user cosmic https://apt.pop-os.org/cosmic/cosmic.flatpakrepo
```

Waiting on its addition to Flathub itself (which seems like it will be allowed). Last thing to do then will be to add that "download from Flathub" button - I'll make a PR for that when it's ready.

**Comment by CarsonBurke** [comment]
@Hyperchaotic Can you download it and try it out? When I first open it on Plasma or Cosmic, it only shows the icon and no charts, except in the popup window. I'm wondering if that's just a me thing or a default state - if it is that might be a problem.

Second is that some toggles don't work (actually they can be toggled false but not true, and the visuals don't sync) on Plasma/non cosmic DEs. I would guess this is because the config files are accessed differently on COSMIC or something? 

I can include video if that helps for either of these.

**Comment by Hyperchaotic** [comment]
it never shows up in panel for me, journalctls gives me:
```
Jun 18 18:49:05 pop-os cosmic-panel[2961]: com.system76.CosmicAppletStatusArea: Acquired bus name: org.kde.StatusNotifierWatcher
Jun 18 18:49:05 pop-os cosmic-panel[2961]: com.system76.CosmicAppletStatusArea: Error getting config: com.system76.CosmicTk [GetKey("monospace_font", Os { code: 2, kind: NotFound, message: ">
Jun 18 18:49:05 pop-os cosmic-panel[2961]: com.system76.CosmicAppletTiling: Error getting config: com.system76.CosmicTk [GetKey("monospace_font", Os { code: 2, kind: NotFound, message: "No s>
Jun 18 18:49:05 pop-os cosmic-panel[2961]: com.system76.CosmicAppletBattery: Error getting config: com.system76.CosmicTk [GetKey("monospace_font", Os { code: 2, kind: NotFound, message: "No >
Jun 18 18:49:05 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: error: Unknown socket type inherit-wayland-socket, valid types are: x11, wayland, pulseaudio, session-bus, s>
Jun 18 18:49:05 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: exited with code 1
Jun 18 18:49:06 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: error: Unknown socket type inherit-wayland-socket, valid types are: x11, wayland, pulseaudio, session-bus, s>
Jun 18 18:49:06 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: exited with code 1
Jun 18 18:49:06 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: error: Unknown socket type inherit-wayland-socket, valid types are: x11, wayland, pulseaudio, session-bus, s>
Jun 18 18:49:06 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: exited with code 1
Jun 18 18:49:06 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: error: Unknown socket type inherit-wayland-socket, valid types are: x11, wayland, pulseaudio, session-bus, s>
Jun 18 18:49:06 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: exited with code 1
Jun 18 18:49:07 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: error: Unknown socket type inherit-wayland-socket, valid types are: x11, wayland, pulseaudio, session-bus, s>
Jun 18 18:49:07 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: exited with code 1
Jun 18 18:49:09 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: error: Unknown socket type inherit-wayland-socket, valid types are: x11, wayland, pulseaudio, session-bus, s>
Jun 18 18:49:09 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: exited with code 1
Jun 18 18:49:09 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: error: Unknown socket type inherit-wayland-socket, valid types are: x11, wayland, pulseaudio, session-bus, s>
Jun 18 18:49:09 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: exited with code 1
Jun 18 18:49:09 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: error: Unknown socket type inherit-wayland-socket, valid types are: x11, wayland, pulseaudio, session-bus, s>
Jun 18 18:49:09 pop-os cosmic-panel[2961]: io.github.cosmic_utils.minimon-applet: exited with code 1
```

**Comment by Hyperchaotic** [comment]
If I launch with flatpak run, i get charts. The toggles in General setting work but if I toggle on symbols there are just bigger spaces without symbols. The toggle under CPU settings stays "on" when i click them..

**Comment by edfloreshz** [comment]
@Hyperchaotic Try upgrading your system, you need a newer version of `flatpak` which Pop just merged.

**Comment by Hyperchaotic** [comment]
Thank you @edfloreshz ! It shows up in the panel now!  

Problems:

- The problem with toggles not working consistently.
- NVidia GPU isn't detected in panel but it is when using "flatpak run". Perhaps I can look at `journalctl SYSLOG_IDENTIFIER=cosmic-applet-minimon` later.

But gotta go help my kid with Calculus.

**Comment by Hyperchaotic** [comment]
> [@Hyperchaotic](https://github.com/Hyperchaotic) Can you download it and try it out? When I first open it on Plasma or Cosmic, it only shows the icon and no charts, except in the popup window. I'm wondering if that's just a me thing or a default state - if it is that might be a problem.

I’ve seen this a few times when working on features (regular mode, not Flatpak), the app always automagically gets a ConfigChanged message when starting but in those occasions it didn’t. Look in the log for “Message::ConfigChanged()” just after init. For me it always worked fine in next compile and was exceedingly rare so I couldn’t chase it. I was starting to wonder if I could force a config read/load on init instead of just hoping it’d happen.

It’s also weird it shows no charts in that case, even if it doesn’t get its ConfigChanged message (with the config from disk) as the Default() is e.g. CPU chart=true. But if you can reproduce consistently we can start looking at logs!

> Second is that some toggles don't work (actually they can be toggled false but not true, and the visuals don't sync) on Plasma/non cosmic DEs. I would guess this is because the config files are accessed differently on COSMIC or something?
> 
> I can include video if that helps for either of these.

Dunno, let’s start by examining logs, all messages are logged including parameters. Let’s see if there’s a ConfigChanged message after each toggle message. I’m starting to wonder about our connection to the config daemon in Flatpak mode…

**Comment by Hyperchaotic** [comment]
Logs:

```
Jun 19 12:03:27 pop-os cosmic-applet-minimon[20200]: System memory: 33293766656 / 31.01 GB
Jun 19 12:03:27 pop-os cosmic-applet-minimon[20200]: Ignoring unknown button type:
Jun 19 12:03:27 pop-os cosmic-applet-minimon[20200]: Ignoring unknown button type:
Jun 19 12:03:27 pop-os cosmic-applet-minimon[20200]: Message::ConfigChanged()
Jun 19 12:03:27 pop-os cosmic-applet-minimon[20200]: path stroking failed
Jun 19 12:03:27 pop-os cosmic-applet-minimon[20200]: path stroking failed
Jun 19 12:04:30 pop-os cosmic-applet-minimon[20200]: Message::Settings(Some(General))
Jun 19 12:04:34 pop-os cosmic-applet-minimon[20200]: Message::ToggleTightSpacing(true)
Jun 19 12:04:34 pop-os cosmic-applet-minimon[20200]: save_config()
Jun 19 12:04:34 pop-os cosmic-applet-minimon[20200]: Error writing config Read-only file system (os error 30) at path "/home/hyper/.var/app/io.github.cosmic_utils.minimon-applet/config/cosmic/io.github.cosmic_utils.minimon-applet-panel/v1/.atomicwriteQ8eUB5"
Jun 19 12:04:54 pop-os cosmic-applet-minimon[20200]: Message::Settings(None)
Jun 19 12:04:55 pop-os cosmic-applet-minimon[20200]: Message::Settings(Some(Memory))
Jun 19 12:04:58 pop-os cosmic-applet-minimon[20200]: Message::ToggleMemoryPercentage(true)
Jun 19 12:04:58 pop-os cosmic-applet-minimon[20200]: save_config()
Jun 19 12:04:58 pop-os cosmic-applet-minimon[20200]: Error writing config Read-only file system (os error 30) at path "/home/hyper/.var/app/io.github.cosmic_utils.minimon-applet/config/cosmic/io.github.cosmic_utils.minimon-applet-panel/v1/.atomicwriteOcBqAP"
```

Seems like a simple permission issue.

**Comment by Hyperchaotic** [comment]
Concerning Nivida driver I get this when run it:
```
Jun 19 12:03:26 pop-os cosmic-applet-minimon[20200]: Connection to NVML failed, reason: NVIDIA driver is not loaded
```

However the older flatpak image I made with flatpak-builder, run with `flatpak run io.cosmicUtils.cosmicAppletMinimon` gives me this: 
```
Jun 19 12:11:49 pop-os cosmic-applet-minimon[21308]: Successfully connected to NVML
```

So something is missing in the repo version. I can't try it out anew as `just flatpak-builder` doesn't work anymore:

```
Building module cosmic-applet-minimon in /home/hyper/code/minimon-applet/.flatpak-builder/build/cosmic-applet-minimon-1
========================================================================
Running: cargo --offline fetch --manifest-path Cargo.toml --verbose
FB: Running: flatpak build --die-with-parent --env=FLATPAK_BUILDER_BUILDDIR=/run/build/cosmic-applet-minimon --nofilesystem=host:reset --filesystem=/home/hyper/code/minimon-applet/.flatpak-builder/build/cosmic-applet-minimon-1 --bind-mount=/run/build/cosmic-applet-minimon=/home/hyper/code/minimon-applet/.flatpak-builder/build/cosmic-applet-minimon-1 --build-dir=/run/build/cosmic-applet-minimon --bind-mount=/run/ccache=/home/hyper/code/minimon-applet/.flatpak-builder/ccache --env=SOURCE_DATE_EPOCH=1750360690 '--env=CFLAGS=-O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer ' '--env=CXXFLAGS=-O2 -pipe -g -Wp,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer ' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed ' --env=CARGO_HOME=/run/build/cosmic-applet-minimon/cargo --env=CCACHE_DIR=/run/ccache --env=PATH=/run/ccache/bin:/app/bin:/usr/bin:/usr/lib/sdk/rust-stable/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --env=FLATPAK_BUILDER_N_JOBS=20 /home/hyper/code/minimon-applet/.flatpak-builder/rofiles/rofiles-9ek8wr /bin/sh -c 'cargo --offline fetch --manifest-path Cargo.toml --verbose'
error: manifest path `Cargo.toml` does not exist
Error: module cosmic-applet-minimon: Child process exited with code 101
FB: Unmounting read-only fs: fusermount -uz /home/hyper/code/minimon-applet/.flatpak-builder/rofiles/rofiles-9ek8wr
error: Recipe `flatpak-builder` failed on line 102 with exit code 1
```

**Comment by Hyperchaotic** [comment]
I wonder if the flatpak-builder process figured out my machine uses Nvidia and included the dependency. If so we need to specify it explicitly. Just a guess...

**Comment by CarsonBurke** [comment]
Hmm ok, lemme try flatpak builder and see if it's fine for me. It might just be a Nvidia thing

**Comment by CarsonBurke** [comment]
It built fine for me, fresh clone.

The no Cargo.toml seems like you're using an older commit or something. It should definitely be able to find the Cargo.toml... sorry I don't know how to debug that further.

**Comment by CarsonBurke** [comment]
In regards to the Nvidia error: I removed the `--devices=all` flag as I didn't see issues. I would guess that it effects nvml? Try adding that back in to the json manifest and see if it works again? If so we should add that back in and make an exception on Flathub.

Sorry for not asking you/testing that change.

**Comment by Hyperchaotic** [comment]
Strange, I get same error on Fedora, fresh clone, then "just flatpak-builder". Is there anything I need to run first?

--devices=all is needed as nvml requires access to /dev/nvidia*

Hopefully with devices=all and figuring out the .var permission issue a lot should be cleared up :)

**Comment by CarsonBurke** [comment]
hmm @edfloreshz would you mind trying as well? Or thoughts?

**Comment by edfloreshz** [comment]
I'm not an NVIDIA user so I'm not sure I can contribute to this, but if it helps, I'm not able to see anything under GPU/Graphics.

**Comment by CarsonBurke** [comment]
The assistance would be to see if you have any issues building with `just flatpak-builder` or if you know why it's throwing the Cargo.toml not found error

**Comment by CarsonBurke** [comment]
~~@Hyperchaotic apologies, it seems that I only removed the `devices=all` from the flathub manifest json. So it is still enabled for this repo and is likely not the cause of your problem.~~

ignore this if you're building it from the cosmic flatpak command I provided, which I think you are.

**Comment by CarsonBurke** [comment]
[pr](https://github.com/pop-os/cosmic-flatpak/pull/1) should address that. Sorry

**Comment by Hyperchaotic** [comment]
Summarizing issues I see:

- Unable to save config file to read-only location (so toggles appear frozen, etc)
- No Nvidia GPU (should get fixed with "device=all" PR)
- Symbolic icons missing, it shows app icon for each instead. I wonder if they're named wrong with hyphen in their names, instead of underscores?

![Image](https://github.com/user-attachments/assets/10e8b115-308f-4184-92ec-406d0827630c)

**Comment by CarsonBurke** [comment]
1. How can we make it a non read-only location? 
2. Yep
3. Lol sorry, I almost certainly did exactly that as I didn't check the icons when I changed the names. I haven't been able to toggle them on since I haven't hopped back to cosmic, except for a second where I confirmed I'm still getting insane vram leakage. I'll submit a PR.

**Comment by Hyperchaotic** [comment]
Yeah, 3) is my bad, if that's the reason, I put hyphens in the names "-ram"/etc. to begin with.

According to Flatseal the XDG-CONFIG is read only, it should be read/write. If I change it to `xdg-config/cosmic:rw` in Flatseal it works. 

![Image](https://github.com/user-attachments/assets/83ac8140-00dc-4fe2-a50e-dd9559472dd1)

**Comment by Hyperchaotic** [comment]
I hope this works. Commit d42a940: Update io.github.cosmic_utils.minimon-applet.json: Give write access to xdg-config/cosmic.

**Comment by CarsonBurke** [comment]
Awesome!

**Comment by CarsonBurke** [comment]
In regards to 1. the icon names do actually seem to be correct

**Comment by Hyperchaotic** [comment]
It looks like the flatpak doesn't have the symbolic icons installed:
```
  ~/.local/share/flatpak/app/io.github.cosmic_utils.minimon-applet ❯ find . -name "*.svg"|grep minimon                                                                                  ✘ 0|1
./x86_64/master/66d58144384313d9d90932b25ba67752bceb263bc5ae1c1cc0dc7e0c200cdd37/export/share/icons/hicolor/scalable/apps/io.github.cosmic_utils.minimon-applet.svg
./x86_64/master/66d58144384313d9d90932b25ba67752bceb263bc5ae1c1cc0dc7e0c200cdd37/files/share/icons/hicolor/scalable/apps/io.github.cosmic_utils.minimon-applet.svg
  ~/.local/share/flatpak/app/io.github.cosmic_utils.minimon-applet ❯
```

**Comment by Hyperchaotic** [comment]
I checked the .json, this part I think is where the symbolic stuff should get installed:
```json
   "build-commands": [
        "cargo --offline fetch --manifest-path Cargo.toml --verbose",
        "cargo --offline build --release --verbose",
        "install -Dm0755 ./target/release/cosmic-applet-minimon /app/bin/cosmic-applet-minimon",
        "install -Dm0644 ./res/io.github.cosmic_utils.minimon-applet.desktop /app/share/applications/io.github.cosmic_utils.minimon-applet.desktop",
        "install -Dm0644 ./res/io.github.cosmic_utils.minimon-applet.metainfo.xml /app/share/metainfo/io.github.cosmic_utils.minimon-applet.metainfo.xml",
        "install -Dm0644 ./res/icons/apps/io.github.cosmic_utils.minimon-applet.svg /app/share/icons/hicolor/scalable/apps/io.github.cosmic_utils.minimon-applet.svg"
      ],
  ```

**Comment by CarsonBurke** [comment]
Sorry I meant to respond, got busy. Yeah we don't build with them, we lost that when we removed usage of just. It's a bit unpleasant but we can just add them to the build commands. Would be preferable to get just working, butni guess that's not realistic.

**Comment by Hyperchaotic** [comment]
Yeah, It would be good to fix the icons in the one built in the COSMIC Flatpak Repository, we don't want a buggy version there :)

Btw, if we make fixes/changes to the minimon repo, when/how is that reflected in the COSMIC Flatpak Repository build?

**Comment by CarsonBurke** [comment]
So it reads from the res/[io.github.cosmic_utils.minimon-applet.metainfo.xml](https://github.com/cosmic-utils/minimon-applet/blob/main/res/io.github.cosmic_utils.minimon-applet.metainfo.xml) file, which has tags for all the info you see displayed like screenshots, icon, changelog, etc. And then some of it is taken from the json. 

If you look at the cosmic-flatpak repo where the json lives, you'll see [the sources array](https://github.com/pop-os/cosmic-flatpak/blob/0905e5969fa0b13ea642fb22201369e6f4c5e38d/app/io.github.cosmic_utils.minimon-applet/io.github.cosmic_utils.minimon-applet.json#L38) is different from the one in our repo. It instead references a specific commit in our repo. So to update the cosmic-flatpak version you'd simply update the commit to the desired newer one.

![Image](https://github.com/user-attachments/assets/0937d5bf-76c0-423a-98a3-0b2379f8ec6f)
*the id for the commit to reference in cosmic-flatpak*

**Comment by Hyperchaotic** [comment]
Interesting so we need to add the missing icons to build-commands in both repos and update the commit hash to pull in the config/frozen toggles fix, then we should be in a good state.

**Comment by Hyperchaotic** [comment]
@CarsonBurke I made a new release and updated the hash in the metadata file. I tested the Flatpak build and things are a whole lot better.

Since you already have a PR open on cosmic-flatpak, perhaps you could review and add the following changes to the json there:

change `"--filesystem=xdg-config/cosmic:ro"` to `"--filesystem=xdg-config/cosmic:rw"`

Add the symbolic icons:
```
     "build-commands": [
        "cargo --offline fetch --manifest-path Cargo.toml --verbose",
        "cargo --offline build --release --verbose",
        "install -Dm0755 ./target/release/cosmic-applet-minimon /app/bin/cosmic-applet-minimon",
        "install -Dm0644 ./res/io.github.cosmic_utils.minimon-applet.desktop /app/share/applications/io.github.cosmic_utils.minimon-applet.desktop",
        "install -Dm0644 ./res/io.github.cosmic_utils.minimon-applet.metainfo.xml /app/share/metainfo/io.github.cosmic_utils.minimon-applet.metainfo.xml",
        "install -Dm0644 ./res/icons/apps/io.github.cosmic_utils.minimon-applet.svg /app/share/icons/hicolor/scalable/apps/io.github.cosmic_utils.minimon-applet.svg",
        "install -Dm0644 ./res/icons/apps/io.github.cosmic_utils.minimon-applet-cpu.svg /app/share/icons/hicolor/scalable/apps/io.github.cosmic_utils.minimon-applet-cpu.svg",
        "install -Dm0644 ./res/icons/apps/io.github.cosmic_utils.minimon-applet-gpu.svg /app/share/icons/hicolor/scalable/apps/io.github.cosmic_utils.minimon-applet-gpu.svg",
        "install -Dm0644 ./res/icons/apps/io.github.cosmic_utils.minimon-applet-harddisk.svg /app/share/icons/hicolor/scalable/apps/io.github.cosmic_utils.minimon-applet-harddisk.svg",
        "install -Dm0644 ./res/icons/apps/io.github.cosmic_utils.minimon-applet-network.svg /app/share/icons/hicolor/scalable/apps/io.github.cosmic_utils.minimon-applet-network.svg",
        "install -Dm0644 ./res/icons/apps/io.github.cosmic_utils.minimon-applet-ram.svg /app/share/icons/hicolor/scalable/apps/io.github.cosmic_utils.minimon-applet-ram.svg",
        "install -Dm0644 ./res/icons/apps/io.github.cosmic_utils.minimon-applet-temperature.svg /app/share/icons/hicolor/scalable/apps/io.github.cosmic_utils.minimon-applet-temperature.svg"
      ],
```

and a new hash:
```
      "sources": [
        {
           "type": "git",
           "url": "https://github.com/cosmic-utils/minimon-applet.git",
           "commit": "21a2ddfcd04e89a526918ae52af442c8cbac248f"
         },
        "cargo-sources.json"
      ]
```

With this the Flatpak applet should be fully functional and we can tell people to use it!

**Comment by CarsonBurke** [comment]
Sweet! I'll add that hopefully tonight.

**Comment by CarsonBurke** [comment]
Done. I suspect we can resolve when [it](https://github.com/pop-os/cosmic-flatpak/pull/1) is merged.

**Comment by Hyperchaotic** [comment]
Merged. Works beautifully. Seems like Minimon is the very first Flatpak COSMIC Applet in COSMIC store, I look forward to seeing more!

![Image](https://github.com/user-attachments/assets/393ef4e9-071c-423b-9e26-362e8e239813)

**Comment by Hyperchaotic** [comment]
Thank you for the monumental effort @CarsonBurke , Flatpak is a bit of a Gordian Knot.

**Comment by CarsonBurke** [comment]
🥳 Honestly it wasn't much work, and I had lots of help. Thank you for making an applet worth packaging :)
